//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SPOT_MFUpdate.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::_cctor___STATIC__VOID,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::Initialize___STATIC__I4__U4__U4__U4__U2__U2__I4__I4__I4__I4__STRING,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::Authenticate___STATIC__BOOLEAN__I4__SZARRAY_U1,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::Open___STATIC__BOOLEAN__I4,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::Create___STATIC__BOOLEAN__I4,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::GetMissingPackets___STATIC__VOID__I4__SZARRAY_U4,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::AddPacket___STATIC__BOOLEAN__I4__I4__SZARRAY_U1__SZARRAY_U1,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::Validate___STATIC__BOOLEAN__I4__SZARRAY_U1,
    Library_SPOT_MFUpdate_SPOT_MFUpdate_MFNativeUpdate::Install___STATIC__BOOLEAN__I4__SZARRAY_U1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_SPOT_MFUpdate =
{
    "SPOT.MFUpdate", 
    0x00810462,
    method_lookup,
    ////////////////////////////////////////////////////////////////////////////////////
    // check if the version bellow matches the one in AssemblyNativeVersion attribute //
    ////////////////////////////////////////////////////////////////////////////////////
    { 1, 0, 0, 0 }
};
