//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "Process_Watchdog.h"

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    Library_Process_Watchdog_Process_Watchdog_Watchdog::WatchdogManagedInitNative___STATIC__VOID,
    Library_Process_Watchdog_Process_Watchdog_Watchdog::WatchdogManagedResetNative___STATIC__VOID,
    Library_Process_Watchdog_Process_Watchdog_Watchdog::GetWatchdogResetReasonNative___STATIC__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Process_Watchdog =
{
    "Process.Watchdog",
    0xFC0BE260,
    method_lookup,
    { 1, 0, 0, 0 }
};
