//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef _PROCESS_WATCHDOG_H_
#define _PROCESS_WATCHDOG_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>

struct Library_Process_Watchdog_Process_Watchdog_Watchdog
{
    NANOCLR_NATIVE_DECLARE(WatchdogManagedInitNative___STATIC__VOID);
    NANOCLR_NATIVE_DECLARE(WatchdogManagedResetNative___STATIC__VOID);
    NANOCLR_NATIVE_DECLARE(GetWatchdogResetReasonNative___STATIC__U4);

    //--//

};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Process_Watchdog;

#endif  //_PROCESS_WATCHDOG_H_
