//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NETIF_H_
#define _NETIF_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
struct Library_NETIF_NETIF_MacAddress
{
    NANOCLR_NATIVE_DECLARE(NativeUpdate___STATIC__BOOLEAN__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NETIF;

#endif  //_NETIF_H_
