//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "NETIF.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_NETIF_NETIF_MacAddress::NativeUpdate___STATIC__BOOLEAN__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NETIF =
{
    "NETIF", 
    0xB5765D2B,
    method_lookup,
    ////////////////////////////////////////////////////////////////////////////////////
    // check if the version bellow matches the one in AssemblyNativeVersion attribute //
    ////////////////////////////////////////////////////////////////////////////////////
    { 1, 0, 0, 0 }
};
