# This is a cmake configuration file for nanoFramework on STM32F769I DISCOVERY board
# Date created: 12.09.2019 (mku)
# cmake documentation: https://cmake.org/cmake/help/latest/command/set.html

set(API_Hardware.Esp32 OFF CACHE BOOL "option for Hardware.Esp32")
set(API_Hardware.Stm32 ON CACHE BOOL "option for Hardware.Stm32")
set(API_nanoFramework.Devices.Can ON CACHE BOOL "option for nanoFramework.Devices.Can")
set(API_nanoFramework.Devices.OneWire OFF CACHE BOOL "option for nanoFramework.Devices.OneWire")
set(API_nanoFramework.ResourceManager ON CACHE BOOL "option for nanoFramework.ResourceManager")
set(API_nanoFramework.System.Text ON CACHE BOOL "option for nanoFramework.System.Text")
set(API_nanoFramework.System.Collections ON CACHE BOOL "option for nanoFramework.System.Collections")
set(API_System.Devices.Dac OFF CACHE BOOL "option for System.Devices.Dac API")
set(API_System.Math ON CACHE BOOL "option for System.Math")
set(API_System.Net ON CACHE BOOL "option for System.Net")
set(API_Windows.Devices.Adc OFF CACHE BOOL "option for Windows.Devices.Adc API")
set(API_Windows.Devices.Gpio ON CACHE BOOL "option for Windows.Devices.Gpio API")
set(API_Windows.Devices.I2c ON CACHE BOOL "option for Windows.Devices.I2c API")
set(API_Windows.Devices.Pwm OFF CACHE BOOL "option for Windows.Devices.Pwm API")
set(API_Windows.Devices.SerialCommunication ON CACHE BOOL "option for Windows.Devices.SerialCommunication API")
set(API_Windows.Devices.Spi OFF CACHE BOOL "option for Windows.Devices.Spi API")
set(API_Windows.Networking.Sockets OFF CACHE BOOL "option for Windows.Networking.Sockets (Deprecated)")
set(API_Windows.Storage ON CACHE BOOL "option for Windows.Storage")
set(BUILD_VERSION 1.2.4.0 CACHE STRING "Build Version")
#set(CMAKE_BUILD_TYPE MinSizeRel CACHE STRING "Select Build Type")
set(CHIBIOS_BOARD 2G_M4-MCU CACHE STRING "Select the target ChibiOS board")
set(CHIBIOS_CONTRIB_REQUIRED ON CACHE BOOL "option to include ChibiOS Community contributions repository")
set(NF_FEATURE_DEBUGGER ON CACHE BOOL "option to enable support for debugging")
set(NF_FEATURE_HAS_CONFIG_BLOCK ON CACHE BOOL "option to enable configuration block storage")
set(NF_FEATURE_HAS_SDCARD ON CACHE BOOL "option to enable support for SD Card")
set(NF_FEATURE_HAS_USB_MSD ON CACHE BOOL "option to enable USB Mass Storage")
set(NF_FEATURE_RTC ON CACHE BOOL "option to use hardware RTC")
set(NF_FEATURE_USE_APPDOMAINS OFF CACHE BOOL "option to enable Application Domains")
set(NF_FEATURE_USE_FILESYSTEM ON CACHE BOOL "set Filesystem option")
set(NF_FEATURE_USE_NETWORKING ON CACHE BOOL "option to enable networking")
set(NF_FEATURE_USE_SPIFFS OFF CACHE BOOL "option to enable support for SPI file system")
set(NF_FEATURE_SUPPORT_REFLECTION ON CACHE BOOL "option to enable System.Reflection API")
set(NF_FEATURE_WATCHDOG ON CACHE BOOL "option to use hardware watchdog")
set(NF_NETWORKING_SNTP ON CACHE BOOL "option to use add SNTP support, requires networking otherwise has no effect")
set(NF_SECURITY_MBEDTLS ON CACHE BOOL "option to use mbed TLS as the network security provider")
set(RTOS CHIBIOS CACHE STRING "Select RTOS")
set(SUPPORT_ANY_BASE_CONVERSION ON CACHE BOOL "option to enable support for converting strings to value on any base")
set(SWO_OUTPUT OFF CACHE BOOL "option to enable SWO Output")
set(SERIAL_DEBUG_OUTPUT OFF CACHE BOOL "option to enable debug output via DEBUG Z")
set(TARGET_SERIES STM32F4xx CACHE STRING "Series of the target MCU")
set(NF_INTEROP_ASSEMBLIES USB.Host Oberon.NaCl System.IO.FileSystem SPOT.MFUpdate Process.Watchdog CACHE STRING "option to add nanoFramework Interop Libraries")