//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "USB_Host.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_USB_Host_USB_Host_Info::NativeIsDevicePresent___STATIC__BOOLEAN,
    Library_USB_Host_USB_Host_Info::NativeGetVID___STATIC__U2,
    Library_USB_Host_USB_Host_Info::NativeGetPID___STATIC__U2,
    Library_USB_Host_USB_Host_Info::NativeGetSerialNumber___STATIC__STRING,
    Library_USB_Host_USB_Host_Info::NativeGetManufacturerString___STATIC__STRING,
    Library_USB_Host_USB_Host_Info::NativeGetProductString___STATIC__STRING,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_USB_Host =
{
    "USB.Host", 
    0xAA48C67A, //0xA59604BC,
    method_lookup,
    ////////////////////////////////////////////////////////////////////////////////////
    // check if the version bellow matches the one in AssemblyNativeVersion attribute //
    ////////////////////////////////////////////////////////////////////////////////////
    { 1, 0, 0, 0 }
};
