//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _USB_HOST_H_
#define _USB_HOST_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
struct Library_USB_Host_USB_Host_Info
{
    NANOCLR_NATIVE_DECLARE(NativeIsDevicePresent___STATIC__BOOLEAN);
    NANOCLR_NATIVE_DECLARE(NativeGetVID___STATIC__U2);
    NANOCLR_NATIVE_DECLARE(NativeGetPID___STATIC__U2);
    NANOCLR_NATIVE_DECLARE(NativeGetSerialNumber___STATIC__STRING);
    NANOCLR_NATIVE_DECLARE(NativeGetManufacturerString___STATIC__STRING);
    NANOCLR_NATIVE_DECLARE(NativeGetProductString___STATIC__STRING);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_USB_Host;

#endif  //_USB_HOST_H_
