//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _OBERON_NACL_H_
#define _OBERON_NACL_H_

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
struct Library_Oberon_NaCl_Oberon_NaCl_CryptoBox
{
    static const int FIELD_STATIC___random = 0;
    static const int FIELD_STATIC___lock = 1;


    //--//

};

struct Library_Oberon_NaCl_Oberon_NaCl_CryptoSecretBox
{
    static const int FIELD_STATIC__KeyBytes = 2;
    static const int FIELD_STATIC__NonceBytes = 3;
    static const int FIELD_STATIC__ZeroBytes = 4;
    static const int FIELD_STATIC__BoxZeroBytes = 5;


    //--//

};

struct Library_Oberon_NaCl_Oberon_NaCl_CryptoSign
{
    static const int FIELD_STATIC___random = 6;
    static const int FIELD_STATIC___lock = 7;


    //--//

};

struct Library_Oberon_NaCl_Oberon_NaCl_CryptoVerify
{
    static const int FIELD_STATIC__Bytes16 = 8;
    static const int FIELD_STATIC__Bytes32 = 9;


    //--//

};

struct Library_Oberon_NaCl_Oberon_NaCl_Native
{
    NANOCLR_NATIVE_DECLARE(Crypto_compatibility_check___STATIC__I4);
    NANOCLR_NATIVE_DECLARE(Crypto_box_compute_keypair___STATIC__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_box___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_box_open___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_box_beforenm___STATIC__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_box_afternm___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_box_open_afternm___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_scalarmult_base___STATIC__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_scalarmult___STATIC__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_sign_compute_keypair___STATIC__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_sign___STATIC__I4__SZARRAY_U1__I4__BYREF_U4__SZARRAY_U1__I4__I4__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_sign_open___STATIC__I4__SZARRAY_U1__I4__BYREF_U4__SZARRAY_U1__I4__I4__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_secretbox___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_secretbox_open___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_stream___STATIC__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_stream_xor___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_onetimeauth___STATIC__I4__SZARRAY_U1__SZARRAY_U1__I4__I4__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_onetimeauth_verify___STATIC__I4__SZARRAY_U1__SZARRAY_U1__I4__I4__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(Crypto_hash___STATIC__I4__SZARRAY_U1__SZARRAY_U1__I4__I4);
    NANOCLR_NATIVE_DECLARE(Crypto_verify_16___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4);
    NANOCLR_NATIVE_DECLARE(Crypto_verify_32___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Oberon_NaCl;

#endif  //_OBERON_NACL_H_
