//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Oberon_NaCl.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_compatibility_check___STATIC__I4,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_box_compute_keypair___STATIC__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_box___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_box_open___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_box_beforenm___STATIC__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_box_afternm___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_box_open_afternm___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_scalarmult_base___STATIC__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_scalarmult___STATIC__I4__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_sign_compute_keypair___STATIC__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_sign___STATIC__I4__SZARRAY_U1__I4__BYREF_U4__SZARRAY_U1__I4__I4__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_sign_open___STATIC__I4__SZARRAY_U1__I4__BYREF_U4__SZARRAY_U1__I4__I4__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_secretbox___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_secretbox_open___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_stream___STATIC__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_stream_xor___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_onetimeauth___STATIC__I4__SZARRAY_U1__SZARRAY_U1__I4__I4__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_onetimeauth_verify___STATIC__I4__SZARRAY_U1__SZARRAY_U1__I4__I4__SZARRAY_U1,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_hash___STATIC__I4__SZARRAY_U1__SZARRAY_U1__I4__I4,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_verify_16___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4,
    Library_Oberon_NaCl_Oberon_NaCl_Native::Crypto_verify_32___STATIC__I4__SZARRAY_U1__I4__SZARRAY_U1__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Oberon_NaCl =
{
    "Oberon.NaCl", 
    0x17260498,
    method_lookup,
    ////////////////////////////////////////////////////////////////////////////////////
    // check if the version bellow matches the one in AssemblyNativeVersion attribute //
    ////////////////////////////////////////////////////////////////////////////////////
    { 1, 0, 0, 0 }
};
